version: '3.8'

services:
  db:
    image: postgres:latest
    networks:
      - bunseki-apuri
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=bunseki
      - POSTGRES_DATABASE=bunseki
      - POSTGRES_PASSWORD=bunseki
      - POSTGRES_PORT=5432
  dashboard:
    build:
      context: ./dashboard
      args:
        APIURL: http://localhost:8081/
        STATICURL: http://localhost:8082/
    ports:
      - "8080:3000"
  static:
    build:
      context: ./client-side
      args:
        APIURL: http://localhost:8081/
    ports:
      - "8082:3002"
  api:
    build:
      context: ./api
      args:
        PG_USER: bunseki
        PG_HOST: db
        PG_DATABASE: bunseki
        PG_PASSWORD: bunseki
        PG_PORT: 5432
    depends_on:
      - db
    ports:
      - "8081:3001"
    environment:
      - NODE_ENV=production
      - PG_USER=bunseki
      - PG_HOST=db
      - PG_DATABASE=bunseki
      - PG_PASSWORD=bunseki
      - PG_PORT=5432
    networks:
      - bunseki-apuri

networks:
  bunseki-apuri:

volumes:
  db-data:
